### Case - df1-də olub  df2-də olmayan (Merge ilə)

In [83]:
import pandas as pd

# 1-ci dataframe (10 sətir, 5 sütun)
df1 = pd.DataFrame({
    'A': range(1, 11),
    'B': list('abcdefghij'),
    'C': range(11, 21),
    'D': range(21, 31),
    'E': range(31, 41)
})

# 2-ci dataframe (eyni data amma 3 sütun çıxarılıb + bəzi sətirlər silinib)
df2 = df1.drop(columns=['C', 'D', 'E']).iloc[:7]  # 7 sətir saxladıq

df1

    A  B   C   D   E
0   1  a  11  21  31
1   2  b  12  22  32
2   3  c  13  23  33
3   4  d  14  24  34
4   5  e  15  25  35
5   6  f  16  26  36
6   7  g  17  27  37
7   8  h  18  28  38
8   9  i  19  29  39
9  10  j  20  30  40

In [84]:
df2

   A  B
0  1  a
1  2  b
2  3  c
3  4  d
4  5  e
5  6  f
6  7  g

In [85]:
result = df1.merge(df2[['B']], on=['B'], how='left', indicator=True)
result

    A  B   C   D   E     _merge
0   1  a  11  21  31       both
1   2  b  12  22  32       both
2   3  c  13  23  33       both
3   4  d  14  24  34       both
4   5  e  15  25  35       both
5   6  f  16  26  36       both
6   7  g  17  27  37       both
7   8  h  18  28  38  left_only
8   9  i  19  29  39  left_only
9  10  j  20  30  40  left_only

In [86]:
only_df1 = result[result['_merge'] == 'left_only']
only_df1

    A  B   C   D   E     _merge
7   8  h  18  28  38  left_only
8   9  i  19  29  39  left_only
9  10  j  20  30  40  left_only

### Case - df1-də olub df2-də olmayan (~isin)

In [95]:
df1

    A  B   C   D   E
0   1  a  11  21  31
1   2  b  12  22  32
2   3  c  13  23  33
3   4  d  14  24  34
4   5  e  15  25  35
5   6  f  16  26  36
6   7  g  17  27  37
7   8  h  18  28  38
8   9  i  19  29  39
9  10  j  20  30  40

In [96]:
df2

   A  B
0  1  a
1  2  b
2  3  c
3  4  d
4  5  e
5  6  f
6  7  g

In [105]:
result = df1[~df1['B'].isin(df2['B'])]
result

    A  B   C   D   E
7   8  h  18  28  38
8   9  i  19  29  39
9  10  j  20  30  40